#!/bin/sh
# ------------------------------------------------------------------------
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------
#
# This script controls standalone Apache ActiveMQ service processes.
# To ensure compatibility to macosx and cygwin we do not utilize
# lsb standard infrastructure for controlling daemons like
# "start-stop-daemon".
#
# See also http://activemq.apache.org/activemq-command-line-tools-reference.html
# for additional commandline arguments
#
# Authors:
# Marc Schoechlin <ms@256bit.org>
# Adapted by Puppet Labs
# Shrinked to a wrapper over the init script that cames with a package to
# comply with the standard.

# ------------------------------------------------------------------------

# activemq   Apache ActiveMQ Service
#
# chkconfig:    345 24 76
#
# description:  Apache ActiveMQ Service
#
### BEGIN INIT INFO
# Provides:          activemq
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO
# CONFIGURATION
ACTIVEMQ_PROCESS="activemq"
ACTIVEMQ_HOME='<%= @activemq_home -%>'
ACTIVEMQ_CONF='<%= @config_path -%>'
ACTIVEMQ_BASE="$ACTIVEMQ_HOME"
ACTIVEMQ_USER='<%= @system_user -%>'
ACTIVEMQ_BIN="${ACTIVEMQ_HOME}/bin/${ACTIVEMQ_PROCESS}"


show_help() {
  cat << EOF
Tasks provided by the sysv init script:
    restart         - stop running instance (if there is one), start new instance
    console         - start broker in foreground, useful for debugging purposes
    status          - check if activemq process is running

EOF
  exit $RET
}

# ------------------------------------------------------------------------
# MAIN

# show help
if [ -z "$1" ];then
 show_help
fi

case "$1" in
  status)
      su -s '/bin/sh' -c "${ACTIVEMQ_BIN} status" - $ACTIVEMQ_USER
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  start)
      su -s '/bin/sh' -c "${ACTIVEMQ_BIN} start" - $ACTIVEMQ_USER
    ;;
  console)
      su -s '/bin/sh' -c "${ACTIVEMQ_BIN} console" - $ACTIVEMQ_USER
    ;;
  stop)
      su -s '/bin/sh' -c "${ACTIVEMQ_BIN} stop" - $ACTIVEMQ_USER
esac
